# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            Schneems
tagline:          'Schneems on Software'
description:      >
  Ruby Hero. Runs <a href='http://keeprubyweird.com'>@keeprubyweird</a>.
  Works for Heroku.
  Posts on performance and best practices.

# cannot have tags inside of description
rss_description:  >
  Ruby Hero.
  Runs @keeprubyweird.
  Works for Heroku.
  Posts on performance and best practices."

url:              https://www.schneems.com
baseurl:          /
rss_path:         feed.xml

author:
  name:           'Richard Schneeman'
  url:            https://twitter.com/schneems

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

BASE_PATH_FOR_RSS: https://www.schneems.com

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-redirect-from

# Assets
assets:
  css_compressor: sass
  compress:
    css: true
    js: false
  autowrite: true
  # cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"

  assets:
    - "*.png"
    - "*.jpg"
    - "*.svg"
    - "*.webm"
    - "*.mp4"
    - "posts.css"
    - "home.css"
    - "*.js"
  digest: true
  sources:
    - "assets"
    - "assets/stylesheets"
    - "assets/images"
    - "assets/javascripts"
    - "assets/posts/img"
    - "_sass"

  features:
    liquid: true

# Random shit from the internet
include: ['dist/.well-known/', '.well-known']
exclude: ['vendor']
