# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Setup
title:            Schneems
tagline:          'Schneems on Software'
description:      "Pronounced like 'schnapps'. Ruby Hero. Helps run <a href='http://keeprubyweird.com'>@keeprubyweird</a>. Works for Heroku. Contributes to Rails. Calls Austin, Tx home."

# cannot have tags inside of description
rss_description:  "Pronounced like 'schnapps'. Ruby Hero. Helps run @keeprubyweird. Works for Heroku. Contributes to Rails. Calls Austin, Tx home."

url:              http://hyde.getpoole.com
baseurl:          /
rss_path:         feed.xml

author:
  name:           'Richard Schneeman'
  url:            https://twitter.com/schneems

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

BASE_PATH_FOR_RSS: http://www.schneems.com



# Random shit from the internet
exclude: [vendor]
